AWSTemplateFormatVersion: "2010-09-09"

Description: "Example that deploys a DigitalOcean droplet with overridden provider config."

Transform:
- "Terraform"

Metadata:
    DigitalOcean:
        token: "this value will override the secret value, if set"

Resources:

    myDroplet:
        Type: "Terraform::DigitalOcean::Droplet"
        Metadata:
            DigitalOcean:
                token: "this value will override the secret value and template metadata value"
        Properties:
            Image: "ubuntu-18-04-x64"
            Name: "mydroplet1"
            Region: "sgp1"
            Size: "s-1vcpu-1gb"

Outputs:

    Ipv4Address:
        Description: "The IP address of the droplet"
        Value: !GetAtt "myDroplet.Ipv4Address"
